//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public string Estado { get; set; }
        public string Sintomas { get; set; }
        public string Diagnostico { get; set; }
        public int MedicoId { get; set; }
        public int UtenteId { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual Utente Utente { get; set; }
    }
}
