//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogIn
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Tipo { get; set; }
    
        public virtual Medico Medico { get; set; }
        public virtual HelpDesk HelpDesk { get; set; }
    }
}
