//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medico
    {
        public Medico()
        {
            this.Utentes = new HashSet<Utente>();
            this.Consultas = new HashSet<Consulta>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Cedula { get; set; }
        public int Nif { get; set; }
        public System.DateTime CheckIn { get; set; }
        public System.DateTime CheckOut { get; set; }
    
        public virtual ICollection<Utente> Utentes { get; set; }
        public virtual ICollection<Consulta> Consultas { get; set; }
        public virtual Proficiencia Proficiencia { get; set; }
        public virtual LogIn LogIn { get; set; }
    }
}
